security:
    providers:
        in_memory:
            memory:
                users:
                    %admin_login%: { password: %admin_password%, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured area"

    access_control:
        - { path: /admin/, roles: ROLE_ADMIN }

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
