parameters:
    remiii_global.fixtureLoader.class: remiii\GlobalBundle\Services\FixtureLoader

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    remiii_global.fixtureLoader :
        class: "%remiii_global.fixtureLoader.class%"
