<?php

namespace remiii\GlobalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InboundContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboundContactRepository extends EntityRepository
{
}
