<?php

namespace remiii\GlobalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotRepository extends EntityRepository
{

    public function getSpotByXAndY ( $x , $y )
    {
        $qb = $this -> _em -> createQueryBuilder ( 's' )
            -> select ( 's' )
            -> from ( $this -> getEntityName ( ) , 's' )
            -> where ( 'ROUND(s.x,3) = :x' )
            -> andWhere ( 'ROUND(s.y,3) = :y' )
            -> setParameter ( 'x', $x )
            -> setParameter ( 'y', $y ) ;
        return $qb -> getQuery ( ) -> getSingleResult( ) ;
    }

    public function getSpotsList ( )
    {
        $qb = $this -> _em -> createQueryBuilder ( 's' )
            -> select ( 's' )
            -> from ( $this -> getEntityName ( ) , 's' )
            -> orderBy ( 's.name', 'ASC' ) ;
        return $qb -> getQuery ( ) -> getResult( ) ;
    }

}
